### PR TITLE
Only import modules that are needed

### PR DESCRIPTION
**Pull request by webberig**
When importing `lodash`, it will added to the bundle entirely, not just the functions that you are using.

You immediately see the difference when building the app inside this repo:
Before:
```
vendor.js                                      | vendor                           |   4.83 MB |
```

After:
```
vendor.js                                      | vendor                           |   4.43 MB |
```

### CODE REVIEW

**Comment by webberig** [comment]
so... this is proving to be more difficult than I expected 😅 
Will do more attempts tomorrow...

**Comment by larscom** [comment]
Hehe, try setting `"esModuleInterop" : true` in tsconfig.json (root of project)  :smile:

**Comment by webberig** [comment]
I was trying to avoid that, but when I realized this is just for the tests, it's fine. Thanks for the tip!

**Comment by larscom** [comment]
Great! thanks

**Pull request merged**
